name: GatorGrader

on:
  push:
    branches: [ main ]

jobs:
  grade:
    runs-on: ubuntu-latest
    steps:
    - uses: gabrielfalcao/pyenv-action@v6
      with: 
        default: 3.6.3 
    - uses: actions/checkout@v2
      with: 
        fetch-depth: '0'
    - name: Set up grading environment
      run: |
        pyenv global 3.6.3
        export PATH="/home/runner/.local/bin:$PATH"
        pip install --upgrade pip
        pip install pipenv
        pip install notebook
        pipenv install --dev --three
        # pipenv run flake8 src
        # pipenv run black --check src
        # pipenv run pylint src
    - name: Grade worksheets
      run: |
        cd worksheets
        gradle grade
        cd ..
      if: always()
    - name: Grade lab
      run: |
        cd lab
        gradle grade
        cd ..
      if: always()
    - name: Grade repository
      run: |
        gradle grade
      if: always()
      env:   
       PIPENV_VENV_IN_PROJECT: 1
       PIPENV_IGNORE_VIRTUALENVS: 1
