---
name: cmpsc-100-week-01-worksheets
break: true
indent: 4
---

Week 01 - Worksheet 0 - Syntax - Expressions.ipynb:
    ConfirmFileExists
    MatchFileFragment --fragment "TODO" --count 0 --exact
    MatchFileFragment --fragment "19334.0" --count 1 --exact
    MatchFileFragment --fragment "16.0" --count 2 --exact
    MatchFileFragment --fragment "86.0" --count 1 --exact
    
Week 01 - Worksheet 1 - Syntax - Assignments.ipynb:
    ConfirmFileExists
    MatchFileFragment --fragment "TODO" --count 0 --exact
    MatchFileFragment --fragment "True" --count 2 --exact
    
Week 01 - Worksheet 2 - Data Types.ipynb:
    ConfirmFileExists
    MatchFileFragment --fragment "TODO" --count 0 --exact
    MatchFileFragment --fragment "4500" --count 3
    MatchFileFragment --fragment "900.0" --count 1 --exact
    MatchFileFragment --fragment "4050.0" --count 1 --exact
    MatchFileFragment --fragment "print(" --count 3